/** @type {import('tailwindcss').Config} */
module.exports = {
      darkMode: "class",
      theme: {
        extend: {
        fontSize: {
          'display-lg': ['32px', '40px'],
          'display-md': ['28px', '36px'],
          'display-sm': ['24px', '32px'],
          'headline-lg': ['24px', '32px'],
          'headline-md': ['20px', '28px'],
          'headline-sm': ['18px', '24px'],
          'title-lg': ['18px', '24px'],
          'title-md': ['16px', '24px'],
          'title-sm': ['14px', '20px'],
          'body-lg': ['16px', '24px'],
          'body-md': ['14px', '20px'],
          'body-sm': ['12px', '16px'],
          'label-lg': ['14px', '20px'],
          'label-md': ['12px', '16px'],
          'label-sm': ['11px', '16px'],
        },
          colors: {
            surface: '#10131b',
            'surface-dim': '#10131b',
            'surface-bright': '#363941',
            'surface-container-lowest': '#0b0e15',
            'surface-container-low': '#181c23',
            'surface-container': '#1c2027',
            'surface-container-high': '#262a32',
            'surface-container-highest': '#31353d',
            'on-surface': '#e0e2ed',
            'on-surface-variant': '#c0c6d6',
            'inverse-surface': '#e0e2ed',
            'inverse-on-surface': '#2d3038',
            outline: '#8b91a0',
            'outline-variant': '#414754',
            'surface-tint': '#aac7ff',
            primary: '#aac7ff',
            'on-primary': '#003064',
            'primary-container': '#3e90ff',
            'on-primary-container': '#002957',
            'inverse-primary': '#005db8',
            secondary: '#c6c6cb',
            'on-secondary': '#2f3034',
            'secondary-container': '#46464b',
            'on-secondary-container': '#b5b4ba',
            tertiary: '#ffb691',
            'on-tertiary': '#552000',
            'tertiary-container': '#eb6a12',
            'on-tertiary-container': '#4a1b00',
            error: '#ffb4ab',
            'on-error': '#690005',
            'error-container': '#93000a',
            'on-error-container': '#ffdad6',
            'primary-fixed': '#d6e3ff',
            'primary-fixed-dim': '#aac7ff',
            'on-primary-fixed': '#001b3e',
            'on-primary-fixed-variant': '#00468d',
            'secondary-fixed': '#e3e2e7',
            'secondary-fixed-dim': '#c6c6cb',
            'on-secondary-fixed': '#1a1b1f',
            'on-secondary-fixed-variant': '#46464b',
            'tertiary-fixed': '#ffdbcb',
            'tertiary-fixed-dim': '#ffb691',
            'on-tertiary-fixed': '#341100',
            'on-tertiary-fixed-variant': '#793100',
            background: '#10131b',
            'on-background': '#e0e2ed',
            'surface-variant': '#31353d'
          }
        }
      }
    };
module.exports.content = ['./*.html', './src/**/*.js'];
